[package]
name = "nanosql"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31.0", features = ["modern_sqlite"] }
thiserror = "1.0.61"
ordered-float = { version = "4.2.0", optional = true }
ptree = { version = "0.4.0", optional = true, default-features = false }
nanosql_macros = { path = "../nanosql_macros", version = "0.1.0", optional = true }

[dev-dependencies]
compiletest_rs = "0.11.0"

[features]
derive = ["dep:nanosql_macros"]
not-nan = ["dep:ordered-float"]
pretty-eqp = ["dep:ptree"]

[[example]]
name = "derive"
test = true
harness = false

[[example]]
name = "indexes"
test = true
harness = false

[[example]]
name = "foreign_key"
test = true
harness = false

[[example]]
name = "unique_and_check"
test = true
harness = false
