[package]
name = "nanosql"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.31.0"
thiserror = "1.0.61"
ordered-float = { version = "4.2.0", optional = true }
nanosql_macros = { path = "../nanosql_macros", version = "0.1.0", optional = true }

[dev-dependencies]
compiletest_rs = "0.11.0"

[features]
derive = ["dep:nanosql_macros"]
not-nan = ["dep:ordered-float"]
